version: '3.8'

services:
  backend:
    image: ${DOCKER_USERNAME}/salesflow-backend:latest
    restart: always
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - EMAIL_SERVER=${EMAIL_SERVER}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch

  frontend:
    image: ${DOCKER_USERNAME}/salesflow-frontend:latest
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:
